# Generated by Django 3.2 on 2026-04-06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("donor", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Payment",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("donor_name", models.CharField(max_length=70)),
                ("email", models.CharField(max_length=100)),
                ("phone", models.CharField(max_length=20)),
                ("amount", models.DecimalField(decimal_places=2, max_digits=10)),
                ("purpose", models.CharField(choices=[("Donation", "Donation"), ("Membership", "Membership"), ("Campaign", "Campaign"), ("Emergency Support", "Emergency Support")], max_length=30)),
                ("payment_method", models.CharField(choices=[("Cash", "Cash"), ("Bank Transfer", "Bank Transfer"), ("eSewa", "eSewa"), ("Khalti", "Khalti")], max_length=30)),
                ("status", models.CharField(choices=[("Pending", "Pending"), ("Completed", "Completed"), ("Failed", "Failed")], default="Completed", max_length=20)),
                ("transaction_id", models.CharField(max_length=40, unique=True)),
                ("remarks", models.CharField(blank=True, max_length=150)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "db_table": "payment",
            },
        ),
    ]
