from django.urls import include, path
from donor import views

urlpatterns = [
    path('api/', include('donor.api_urls')),
    path('', views.home , name="home"),
    path('blog', views.blog , name="blog"),
    path('about', views.about , name="about"),
    path('contact', views.contact , name="contact"),
    path('donor', views.donor , name="donor"),
    path('deletednr/<int:id>/', views.delete_dnr, name = "deletednr"),
    path('updatednr/<int:id>/', views.update_dnr, name = "updatednr"),
    path('updataednr/<int:id>/', views.update_dnr),
    path('bloodreq', views.bloodreq , name="bloodreq"),
    path('deletebreq/<int:id>/', views.delete_breq, name = "deletebreq"),
    path('updatebreq/<int:id>/', views.update_breq, name = "updatebreq"),
    path('updataebreq/<int:id>/', views.update_breq),
    path('stock', views.stock , name="stock"),
    path('deletestk/<int:id>/', views.delete_stk, name = "deletestk"),
    path('updatestk/<int:id>/', views.update_stk, name = "updatestk"),
    path('updataestk/<int:id>/', views.update_stk),
    path('payment', views.payment, name="payment"),
    path('reports', views.reports, name="reports"),
    path('reports/live-data', views.live_report_data, name="live_report_data"),
    path('reports/export/csv', views.export_reports_csv, name="export_reports_csv"),
    path('terms', views.terms , name="terms"),
    path('eligible', views.eligible , name="eligible"),
    path('login', views.login , name = "login" ),
    path('logout', views.logout , name = "logout" ),
    path('register', views.register, name = "register" ),
]
